services:
  twr:
    container_name: twr
    image: arbarwings/docker-web-redirect:latest
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.twr.rule=Host(`taiko-web-is-4ever.yuuk1.tk`) || Host(`taiko-web-v2.yuuk1.tk`)
      - traefik.http.routers.twr.tls=true
      - traefik.http.routers.twr.tls.certResolver=letsencrypt
      - traefik.http.routers.twr.service=twr-routing-service
      - traefik.http.services.twr-routing-service.loadbalancer.server.port=80
    environment:
      - REDIRECT_TARGET=taikoapp.uk

networks:
  traefik:
    external: true
    name: traefik
