services:
  space-cadet-pinball:
    image: nginx:1.25.5
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.R2.rule=Host(`space-cadet-pinball.yuuk1.uk`)
      - traefik.http.routers.R2.entryPoints=websecure
      - traefik.http.routers.R2.tls=true
      - traefik.http.routers.R2.tls.certResolver=letsencrypt
      - traefik.http.routers.R2.service=S2
      - traefik.http.services.S2.loadbalancer.server.port=80
    volumes:
      - ../../repo/space-cadet-pinball:/usr/share/nginx/html

networks:
  traefik:
    external: true
    name: traefik
