services:
  catmario:
    image: nginx:1.26.2
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.R6.rule=Host(`catmario.yuuk1.uk`)
      - traefik.http.routers.R6.entryPoints=websecure
      - traefik.http.routers.R6.tls=true
      - traefik.http.routers.R6.tls.certResolver=letsencrypt
      - traefik.http.routers.R6.service=S6
      - traefik.http.services.S6.loadbalancer.server.port=80
    volumes:
      - ../../repo/catmario/docs:/usr/share/nginx/html

networks:
  traefik:
    external: true
    name: traefik
