services:
  traefik:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/acme
    image: traefik:v3.0.1
    networks:
      - traefik
    command:
      - --log.level=TRACE
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge=true
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.delayBeforeCheck=0
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.letsencrypt.acme.storage=acme/acme.json
      - --api.dashboard=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.yuuk1.uk`)
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certResolver=letsencrypt
      - traefik.http.routers.dashboard.service=api@internal

networks:
  traefik:
    name: traefik
